### ISSUE TITLE
error: only one download client can be enabled at a time, but I only hae one download client configured

### ISSUE THREAD

**Issue by mrjones2014** [flmorg/cleanuperr#20]
I'm running the service via NixOS's API for docker/podman containers.

```nix
{ config, ... }:
let envFile = config.age.secrets.cleanuperr_env.path;
in {
  age.secrets.cleanuperr_env.file = ../../secrets/cleanuperr_env.age;
  virtualisation.oci-containers = {
    backend = "podman";
    containers.cleanuperr = {
      autoStart = true;
      image = "ghcr.io/flmorg/cleanuperr:latest";
      environmentFiles = [ envFile ];
    };
  };
}
```

Where the contents of `config.age.secrets.cleanuperr_env.path` is

```env
QUEUECLEANER__ENABLED=true
CONTENTBLOCKER__ENABLED=true
CONTENTBLOCKER__BLACKLIST__ENABLED=true
CONTENTBLOCKER__BLACKLIST__PATH=https://raw.githubusercontent.com/flmorg/cleanuperr/refs/heads/main/blacklist

DELUGE__ENABLED=true
DELUGE__URL=http://localhost:8112
DELUGE__PASSWORD=[redacted for github]

SONARR__ENABLED=true
SONARR__SEARCHTYPE=Season
SONARR__INSTANCES__0__URL=http://localhost:8989
SONARR__INSTANCES__0__APIKEY=[redacted for github]

RADARR__ENABLED=true
RADARR__INSTANCES__0__URL=http://localhost:7878
RADARR__INSTANCES__0__APIKEY=[redacted for github]
```

Is there anything obvious I'm doing wrong here?

**Comment by mrjones2014** [comment]
<details>
<summary>Click to expand full error logs</summary>

```
Dec 11 10:17:22 nixos-server cleanuperr[678316]: [2024-12-11 15:17:22.613 ERR] An error occurred instantiating job to be executed. job= 'DEFAULT.ContentBlocker, message=only one download client can be enabled'
Dec 11 10:17:22 nixos-server cleanuperr[678316]: Quartz.SchedulerException: Problem instantiating type 'Executable.Jobs.GenericJob`1[[Infrastructure.Verticals.ContentBlocker.ContentBlocker, Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]: only one download client can be enabled'
Dec 11 10:17:22 nixos-server cleanuperr[678316]:  ---> System.Exception: only one download client can be enabled
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Infrastructure.Verticals.DownloadClient.DownloadServiceFactory..ctor(IOptions`1 qBitConfig, IOptions`1 delugeConfig, IOptions`1 transmissionConfig, IServiceProvider serviceProvider) in /app/Infrastructure/Verticals/DownloadClient/DownloadServiceFactory.cs:line 38
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at lambda_method9(Closure, IServiceProvider, Object[])
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.JobActivatorCache.CreateInstance(IServiceProvider serviceProvider, Type jobType)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.CreateJob(TriggerFiredBundle bundle, IServiceProvider serviceProvider)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.InstantiateJob(TriggerFiredBundle bundle, IScheduler scheduler)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.PropertySettingJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Core.JobRunShell.Initialize(QuartzScheduler sched, CancellationToken cancellationToken)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    --- End of inner exception stack trace --- [See nested exception: System.Exception: only one download client can be enabled
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Infrastructure.Verticals.DownloadClient.DownloadServiceFactory..ctor(IOptions`1 qBitConfig, IOptions`1 delugeConfig, IOptions`1 transmissionConfig, IServiceProvider serviceProvider) in /app/Infrastructure/Verticals/DownloadClient/DownloadServiceFactory.cs:line 38
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at lambda_method9(Closure, IServiceProvider, Object[])
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.JobActivatorCache.CreateInstance(IServiceProvider serviceProvider, Type jobType)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.CreateJob(TriggerFiredBundle bundle, IServiceProvider serviceProvider)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.InstantiateJob(TriggerFiredBundle bundle, IScheduler scheduler)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Simpl.PropertySettingJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler)
Dec 11 10:17:22 nixos-server cleanuperr[678316]:    at Quartz.Core.JobRunShell.Initialize(QuartzScheduler sched, CancellationToken cancellationToken)]
```

</details>

**Comment by Flaminel** [comment]
You're going to have to explicitly set `QBITTORRENT__ENABLED=false` if you want to use Deluge. It is enabled by default and I am sorry for the confusion. I'll be working on changing how this part of the configuration works soon enough.

**Comment by mrjones2014** [comment]
Sorry, I'm stupid 😛 

I didn't see that `QBITTORRENT__ENABLED` is `true` by default.

**Comment by mrjones2014** [comment]
I didn't see that `QBITTORRENT__ENABLED` is `true` by default, but I set `QBITTORRENT__ENABLED=false` and I get the same error.

**Comment by mrjones2014** [comment]
Nevermind, sorry for the confusion, GitHub was lagging/glitching there for a minute.
