### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by danielsza** [flmorg/cleanuperr#26]
running the macos arm version

Last login: Thu Dec 26 11:20:55 on ttys001
/Applications/cleanuperr-osx-arm64/cleanuperr ; exit;                           
macserver@macservers ~ % /Applications/cleanuperr-osx-arm64/cleanuperr ; exit;
Unhandled exception. System.InvalidOperationException: Section 'Triggers' not found in configuration.
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.GetRequiredSection(IConfiguration configuration, String key)
   at Executable.DependencyInjection.QuartzDI.<>c__DisplayClass0_0.<AddQuartzServices>b__0(IServiceCollectionQuartzConfigurator q)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, NameValueCollection properties, Action`1 configure)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, Action`1 configure)
   at Executable.DependencyInjection.QuartzDI.AddQuartzServices(IServiceCollection services, IConfiguration configuration)
   at Executable.DependencyInjection.MainDI.AddInfrastructure(IServiceCollection services, IConfiguration configuration)
   at Program.<Main>$(String[] args)
zsh: abort      /Applications/cleanuperr-osx-arm64/cleanuperr

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Flaminel** [comment]
Did you also copy the `appsettings.json` file from the archive in the same place you put the cleanuperr binary?

**Comment by danielsza** [comment]
Yes both files are in the same folderSent from my iPhoneOn Dec 26, 2024, at 11:52, Marius Nechifor ***@***.***> wrote:﻿
Did you also copy the appsettings.json file from the archive in the same place you put the cleanuperr binary?

**Comment by Flaminel** [comment]
It's probably because you're trying to run cleanuperr from outside of its directory. From those logs it seems that you're trying to run `/Applications/cleanuperr-osx-arm64/cleanuperr`, so that means your working directory is something else. cleanuperr is looking for that settings file where you executed the command from. I'd recommend running `cd /Applications/cleanuperr-osx-arm64` before trying to run cleanuperr or copy the configuration file into your working directory.

**Comment by danielsza** [comment]
Looks like the issues was me launching it from the GUI. 

If I launched it from the CLI it works as it should.
